// Generated from the Rust types by src-tauri/src/typescript.rs. Do not edit this file: change the Rust
// type, then write it again with `NUZKY_WRITE_TYPES=1 cargo test -p nuzky-app typescript_types`.

/**
 * Colour adjustments, all 0 by default (no change). Ranges are -1..=1 except fade and vignette 0..=1.
 */
export type Adjust = {
  /**
   * Linear-light exposure, -2 to +2 stops.
   */
  exposure: number,
  /**
   * Negative shifts green, positive shifts magenta.
   */
  tint: number,
  highlights: number,
  shadows: number,
  fade: number,
  brightness: number,
  contrast: number,
  saturation: number,
  /**
   * Negative cools (blue), positive warms (orange).
   */
  temperature: number,
  vignette: number,
};

/**
 * An agent Nuzky can be connected to, and the state of its `nuzky` MCP entry.
 */
export type AgentConnection = {
  agent: AgentKind,
  name: string,
  /**
   * Its config file.
   */
  path: string,
  /**
   * `connected`: the entry runs this app. `other`: a `nuzky` entry runs something else. `missing`: no
   * `nuzky` entry. `unreadable`: the file is not valid, and connecting would not touch it.
   */
  state: "connected" | "other" | "missing" | "unreadable",
  /**
   * Why the file could not be read.
   */
  problem: string | null,
  /**
   * The copy made before the last change.
   */
  backup: string | null,
};

export type AgentKind = "claudeCode" | "codex";

export type Animation = {
  kind: AnimationKind,
  durationUs: number,
};

export type AnimationKind = "fade" | "zoomIn" | "zoomOut" | "slideUp" | "slideDown" | "slideLeft" | "slideRight" | "pop" | "typewriter";

export type AnimationSlot = "in" | "out";

export type Asset = {
  id: string,
  name: string,
  path: string,
  kind: AssetKind,
  /**
   * 0 for still images.
   */
  durationUs: number,
  /**
   * Display size, after applying rotation metadata.
   */
  width: number,
  height: number,
  fps: number,
  hasAudio: boolean,
  /**
   * Clockwise rotation from container metadata (0, 90, 180, 270).
   */
  rotation: number,
  /**
   * Mirrored left to right after the rotation, as front-camera photos can ask in EXIF.
   */
  mirror?: boolean,
  /**
   * Where a sound from the sound library came from, so the video can credit it. None for the
   * user's own files.
   */
  credit?: Credit | null,
};

export type AssetKind = "video" | "audio" | "image";

export type Boot = {
  limits: Limits,
  snapshot: Snapshot,
  previewUrl: string,
  transport: Transport,
  /**
   * Why the preview could not start, when it failed before the UI listened.
   */
  engineError: string | null,
  /**
   * Why the most recent project was not opened, when another one opened instead.
   */
  startupNotice: string | null,
  version: string,
  /**
   * False when `NUZKY_NO_UPDATE_CHECK=1`: Nuzky then never asks whether a newer version exists.
   */
  updateChecks: boolean,
};

/**
 * The canvas as the UI receives it. Snapshots add its safe area (`snapshot_project` in lib.rs), which
 * saved projects leave out.
 */
export type Canvas = {
  /**
   * Where Reels and TikTok draw nothing over a vertical video, in canvas pixels; null for other formats.
   */
  safeArea: SafeArea | null,
  width: number,
  height: number,
  fps: number,
  /**
   * `#rrggbb`
   */
  background: string,
  /**
   * 0 keeps the solid background. Above 0 a blurred, canvas-filling copy of the
   * main-track frame shows behind it (CapCut "Canvas: Blur"); 1 is the strongest blur.
   */
  backgroundBlur: number,
};

export type CaptionSegment = {
  startUs: number,
  endUs: number,
  text: string,
  /**
   * The spoken words, with TIMELINE times, for karaoke styles; their texts joined by single spaces
   * must be `text`. The clip stores them relative to its start.
   */
  words: Array<CaptionWord>,
};

/**
 * One spoken word of a caption. Times are relative to the clip start, like keyframes, so moving
 * the clip keeps them; a trim may leave some outside the clip, where they never show.
 */
export type CaptionWord = {
  text: string,
  startUs: number,
  endUs: number,
};

export type Clip = {
  id: string,
  startUs: number,
  durationUs: number,
  content: ClipContent,
  /**
   * Entry animation over the first `duration_us` of the clip.
   */
  animIn: Animation | null,
  /**
   * Exit animation over the last `duration_us` of the clip.
   */
  animOut: Animation | null,
  /**
   * Transform keyframes, `t_us` relative to the clip start. When present they replace
   * the content transform and are interpolated along each keyframe's `ease`; outside the
   * range the nearest keyframe holds.
   */
  keyframes: Array<Keyframe>,
  /**
   * Main track only: transition from the previous clip, centred on the cut.
   */
  transitionIn: Transition | null,
};

export type ClipContent = {
  "type": "media",
  assetId: string,
  sourceInUs: number,
  volume: number,
  transform: Transform,
  /**
   * Playback speed; the clip covers `duration_us * speed` of source. Sound follows it.
   */
  speed: number,
  /**
   * Sound at another speed keeps its pitch; off, it gets higher when faster and lower
   * when slower. Projects from before it have it off, so they sound as they did.
   */
  keepPitch?: boolean,
  adjust: Adjust,
  /**
   * Audio fades at the clip edges.
   */
  fadeInUs: number,
  fadeOutUs: number,
  /**
   * Clean voice: a high-pass against rumble and hum, gentle noise reduction and a de-esser,
   * for speech recorded on a phone. Only clips with sound. Playback uses the original sound
   * until the cleaned sound is prepared; export always has the cleaned sound.
   */
  cleanVoice: boolean,
  /**
   * Rounded corners, a border and a shadow around the picture, as for a picture in picture.
   */
  shape?: Shape | null,
  /**
   * Ducking, for music under speech: how many dB the clip goes down while someone speaks in
   * a video's own sound, coming back in the pauses. 0 turns it off.
   */
  duckDb?: number,
} | {
  "type": "text",
  text: string,
  style: TextStyle,
  transform: Transform,
  /**
   * The spoken words of a generated caption, in order, so `style.highlight` can mark the one
   * being said. They count only while `text` is exactly their texts joined by single spaces;
   * after a manual edit of the text nothing is highlighted.
   */
  words?: Array<CaptionWord>,
};

export type Collection = {
  id: string,
  name: string,
};

/**
 * One frame worth a cover, for the filmstrip of the cover editor.
 */
export type CoverCandidate = {
  timeUs: number,
  score: number,
  /**
   * Each 0..1, higher is better: sharpness and exposure, and with a face eyes_open, mouth, facing,
   * smile, framing_9x16 and framing_16x9.
   */
  parts: {
    [key in string]: number
  },
  face: boolean,
  /**
   * A JPEG data URL of the frame, about 240 pixels on its long side.
   */
  still: string,
};

/**
 * What Pick for me found, as the `output` of its job: candidates best first.
 */
export type CoverPick = {
  format: ThumbnailFormat,
  candidates: Array<CoverCandidate>,
};

/**
 * What the cover canvas shows besides its pixels.
 */
export type CoverView = {
  width: number,
  height: number,
  timeUs: number,
  /**
   * Each text's corners in thumbnail pixels (top-left, top-right, bottom-right, bottom-left); null
   * for a text that is not drawn.
   */
  bounds: Array<[[number, number], [number, number], [number, number], [number, number]] | null>,
  /**
   * The share of each text the person covers, 0..1.
   */
  hidden: Array<number>,
  /**
   * Where the frame is drawn, as for a clip: the corners of its visible part and of the whole frame.
   */
  frame: [[[number, number], [number, number], [number, number], [number, number]], [[number, number], [number, number], [number, number], [number, number]]],
  /**
   * The cover cuts the person out of the frame and their mask is not made yet, so it is drawn
   * without: text behind the person in front of them and no outline.
   */
  maskMissing: boolean,
};

/**
 * A sound from the library: its source, author and licence.
 */
export type Credit = {
  /**
   * "nuzky" for the sounds built into Nuzky, "openverse" or "freesound".
   */
  source: string,
  /**
   * The sound's id at its source.
   */
  id: string,
  title: string,
  author: string,
  license: License,
  /**
   * Such as "4.0" or "1.0".
   */
  licenseVersion: string,
  /**
   * The licence's page at Creative Commons.
   */
  licenseUrl: string,
  /**
   * The sound's page at its source; empty for built-in sounds.
   */
  url: string,
};

/**
 * How much of each edge is cut off, as a fraction of the layer's width (left, right) or height (top,
 * bottom), on the picture as it shows after rotation and mirroring. The rest stays where it was.
 */
export type Crop = {
  left: number,
  top: number,
  right: number,
  bottom: number,
};

/**
 * What Undo needs to bring a deleted collection back.
 */
export type DeletedCollection = {
  collection: Collection,
  /**
   * Where it was in the list.
   */
  position: number,
  paths: Array<string>,
};

/**
 * A platform's delivery format, shared by the export dialog, MCP and the CLI.
 */
export type Delivery = "reels";

export type Ease = "linear" | "smooth";

export type EditCmd = {
  "type": "addAssets",
  assets: Array<Asset>,
} | {
  "type": "removeAsset",
  assetId: string,
} | {
  "type": "addClip",
  assetId: string,
  startUs: number | null,
  trackId: string | null,
} | {
  "type": "addPictureInPicture",
  assetId: string,
  startUs: number,
  durationUs?: number | null,
} | {
  "type": "addText",
  startUs: number,
  text: string,
  style: TextStyle,
} | {
  "type": "moveClip",
  clipId: string,
  trackId: string | null,
  startUs: number,
} | {
  "type": "trimClip",
  clipId: string,
  startUs: number,
  durationUs: number,
  sourceInUs: number | null,
} | {
  "type": "splitClip",
  clipId: string,
  atUs: number,
} | {
  "type": "deleteClips",
  clipIds: Array<string>,
} | {
  "type": "updateClip",
  clipId: string,
  transform?: Transform | null,
  volume?: number | null,
  text?: string | null,
  style?: TextStyle | null,
  /**
   * Changing speed keeps the source range, so the clip gets shorter or longer.
   */
  speed?: number | null,
  /**
   * Sound at another speed keeps its pitch. Moving a clip off 1x turns it on unless the
   * same command sets it.
   */
  keepPitch?: boolean | null,
  adjust?: Adjust | null,
  fadeInUs?: number | null,
  fadeOutUs?: number | null,
  /**
   * Clean voice on clips with sound: less rumble, hum, background noise and harsh s sounds.
   */
  cleanVoice?: boolean | null,
  /**
   * Video and image clips: corners, border and shadow. The default shape removes them.
   */
  shape?: Shape | null,
  /**
   * Ducking: how many dB the clip goes down while a video's own sound has speech, up to 40;
   * 0 turns it off. 12 suits music under speech.
   */
  duckDb?: number | null,
} | {
  "type": "setAnimation",
  clipId: string,
  slot: AnimationSlot,
  animation: Animation | null,
} | {
  "type": "setTransition",
  clipId: string,
  transition: Transition | null,
} | {
  "type": "setKeyframes",
  clipId: string,
  keyframes: Array<Keyframe>,
} | {
  "type": "duplicateClip",
  clipId: string,
} | {
  "type": "detachAudio",
  clipId: string,
} | {
  "type": "updateTrack",
  trackId: string,
  muted?: boolean | null,
  hidden?: boolean | null,
  keepInPlace?: boolean | null,
} | {
  "type": "setCanvas",
  width: number,
  height: number,
  background?: string | null,
  backgroundBlur?: number | null,
} | {
  "type": "addCaptions",
  segments: Array<CaptionSegment>,
  style: TextStyle,
} | {
  "type": "replaceCaptions",
  trackId: string,
  segments: Array<CaptionSegment>,
  style: TextStyle,
} | {
  "type": "rippleDeleteRanges",
  ranges: Array<TimeRange>,
  keepTrackIds?: Array<string> | null,
} | {
  "type": "renameProject",
  name: string,
} | {
  "type": "correctWords",
  corrections: Array<WordCorrection>,
} | {
  "type": "zoomRanges",
  ranges: Array<ZoomRange>,
} | {
  "type": "applyMotion",
  clipId?: string | null,
  range?: TimeRange | null,
  kind: MotionKind,
  /**
   * How far it zooms, as a fraction: 0.06 is subtle, 0.15 strong.
   */
  strength: number,
} | {
  "type": "setThumbnail",
  thumbnail: Thumbnail,
} | {
  "type": "removeThumbnail",
  format: ThumbnailFormat,
};

export type ExportRequest = {
  /**
   * Short side in pixels: 720, 1080, 1440 or 2160.
   */
  resolution: number,
  fps: number,
  /**
   * "high" | "recommended" | "small"
   */
  quality: Quality,
  /**
   * "reels" fixes the format and levels the sound; resolution and fps are then its own.
   */
  preset?: Delivery | null,
};

/**
 * Filmstrip for timeline clips: one horizontal sprite of evenly spaced frames.
 */
export type Filmstrip = {
  /**
   * PNG or JPEG data URL of `count` frames side by side.
   */
  url: string,
  frameWidth: number,
  frameHeight: number,
  /**
   * Source time between consecutive frames.
   */
  intervalUs: number,
  count: number,
};

/**
 * Families the engine can draw: bundled ones ship with Nuzky, system ones are installed on this computer.
 */
export type FontFamilies = {
  bundled: Array<string>,
  system: Array<string>,
};

export type JobEvent = {
  id: string,
  kind: "audio" | "proxy" | "export" | "captions" | "transcript" | "style" | "vision-models" | "cover",
  label: string,
  status: "running" | "done" | "failed" | "cancelled",
  progress: number,
  phase: string | null,
  message: string | null,
  output: string | null,
};

export type Keyframe = {
  tUs: number,
  transform: Transform,
  /**
   * How the values move on to the next keyframe.
   */
  ease: Ease,
};

/**
 * Where a visual layer sits on the canvas at a given time, for selecting and dragging
 * layers directly in the preview.
 */
export type LayerBounds = {
  clipId: string,
  /**
   * Top-left, top-right, bottom-right, bottom-left of the visible part in canvas pixels.
   */
  corners: [[number, number], [number, number], [number, number], [number, number]],
  /**
   * The same corners of the whole layer, before its crop.
   */
  frame: [[number, number], [number, number], [number, number], [number, number]],
};

export type Library = {
  projects: Array<LibraryProject>,
  collections: Array<Collection>,
  /**
   * Set when the collections could not be read.
   */
  notice: string | null,
};

/**
 * A project on the home screen.
 */
export type LibraryProject = {
  path: string,
  name: string,
  modifiedMs: number,
  durationUs: number,
  /**
   * Canvas size; 0 for a project that cannot be read.
   */
  width: number,
  height: number,
  collection: string | null,
  /**
   * `broken`: the file cannot be read. `busy`: another Nuzky window or an agent has it open.
   * `missing`: some of its media files are gone. `empty`: nothing on the timeline.
   */
  state: "broken" | "busy" | "missing" | "empty" | null,
  missing: number,
  /**
   * Why a broken project cannot be read.
   */
  error: string | null,
};

/**
 * The licences the sound library offers: both allow monetized videos.
 */
export type License = "cc0" | "by";

/**
 * Editing limits the engine enforces, sent to the UI at start so it never copies them.
 */
export type Limits = {
  minSpeed: number,
  maxSpeed: number,
  maxTransitionUs: number,
  /**
   * Vertical offset of generated captions from the canvas centre, as a fraction of its height.
   */
  captionY: number,
  maxDuckDb: number,
  minMotionStrength: number,
  maxMotionStrength: number,
};

export type MotionKind = "pushIn" | "pullOut" | "kenBurns";

export type PreviewStarted = {
  durationUs: number,
};

export type Project = {
  version: number,
  name: string,
  canvas: Canvas,
  assets: Array<Asset>,
  /**
   * Compositing order: index 0 is the bottom layer (the main track).
   */
  tracks: Array<Track>,
  /**
   * Recognised words the user corrected. Transcripts belong to the media files and are
   * shared by every project, so the corrections live here.
   */
  wordCorrections?: Array<WordCorrection>,
  /**
   * Covers and thumbnails of the video, at most one per format.
   */
  thumbnails?: Array<Thumbnail>,
};

export type ProjectSummary = {
  path: string,
  name: string,
  modifiedMs: number,
  durationUs: number,
};

/**
 * A kept version of the open project, for the list of versions in the top bar.
 */
export type ProjectVersion = {
  /**
   * Stays with the version across restarts.
   */
  index: number,
  label: string,
  /**
   * Unix time in milliseconds.
   */
  atMs: number,
  /**
   * Made by an AI agent's run.
   */
  ai: boolean,
  /**
   * The project is this version now; only the newest version with its contents says so.
   */
  current: boolean,
};

export type Quality = "high" | "recommended" | "small";

/**
 * Where Instagram Reels and TikTok draw nothing over a vertical video, in canvas pixels: clear of
 * the top bar, the like and comment rail on the right and the caption and buttons at the bottom.
 * Conservative values that suit both apps, from 250 / 180 / 500 / 60 px of 1080×1920.
 */
export type SafeArea = {
  left: number,
  top: number,
  right: number,
  bottom: number,
};

export type Said = {
  hits: Array<SaidHit>,
  /**
   * Projects with speech that is not transcribed, so only their names were searched.
   */
  untranscribed: Array<string>,
  /**
   * How many projects have a transcript to search.
   */
  transcribed: number,
};

/**
 * Where words of a search were said: the project and its timeline time.
 */
export type SaidHit = {
  path: string,
  startUs: number,
  before: string,
  text: string,
  after: string,
};

/**
 * The edge of a video or image layer.
 */
export type Shape = {
  /**
   * Corner radius as a share of half the shorter visible side, 0 to 1. 1 rounds the shorter sides
   * fully: a circle when the crop leaves a square.
   */
  radius: number,
  /**
   * Canvas pixels, drawn outside the edge; 0 draws no border.
   */
  borderWidth: number,
  /**
   * `#rrggbb` or `#rrggbbaa`
   */
  borderColor: string,
  /**
   * A soft shadow under the layer, 0 (none) to 1.
   */
  shadow: number,
};

export type Snapshot = {
  project: Project,
  revision: number,
  sessionEpoch: string,
  /**
   * Label of the AI run editing the project.
   */
  openRunLabel: string | null,
  recovery: boolean,
  canUndo: boolean,
  canRedo: boolean,
  path: string,
  select: Array<string>,
  /**
   * Set when agents cannot attach to this project live; editing works without them.
   */
  agentBridgeError: string | null,
};

/**
 * A sound the library offers.
 */
export type Sound = {
  /**
   * `nuzky:whoosh` for a built-in sound, `openverse:<uuid>` or `freesound:<number>`.
   */
  id: string,
  kind: SoundKind,
  title: string,
  author: string,
  /**
   * 0 when the source does not say.
   */
  durationUs: number,
  license: License,
  licenseVersion: string,
  licenseUrl: string,
  /**
   * The sound's page at its source, where its licence can be checked; empty for built-in sounds.
   */
  url: string,
  /**
   * "Built in", "Jamendo", "Freesound", "Wikimedia Commons"…
   */
  provider: string,
  /**
   * The group of a built-in sound, such as "Whoosh".
   */
  category?: string | null,
};

export type SoundKind = "music" | "effect";

/**
 * One page of online results.
 */
export type SoundPage = {
  sounds: Array<Sound>,
  more: boolean,
  /**
   * "Openverse" or "Freesound": the service the results come from, which the library names.
   */
  service: string,
};

export type SoundSettings = {
  freesound: boolean,
  hasKey: boolean,
};

export type SpeechModel = {
  id: string,
  label: string,
  sizeMb: number,
  downloaded: boolean,
};

/**
 * What the creator, or an agent they agreed with, does to the style.
 */
export type StyleAction = {
  "type": "accept",
  titles: Array<string>,
  seen: Array<string>,
} | {
  "type": "reject",
  title: string,
} | {
  "type": "remove",
  title: string,
} | {
  "type": "revert",
  title: string,
} | {
  "type": "learnAgain",
  title: string,
} | {
  "type": "setOwn",
  index: number | null,
  text: string,
  was: string | null,
} | {
  "type": "setText",
  text: string,
  baseVersion: number,
} | {
  "type": "restore",
  index: number,
} | {
  "type": "reset"
};

export type StyleChange = {
  name: string,
  from: string | null,
  to: string | null,
};

export type StyleConfidence = {
  /**
   * High in 3 or more videos, medium in 2, low in 1.
   */
  level: StyleLevel,
  videos: number,
  /**
   * Videos learned from in all.
   */
  of: number,
  moments: number,
};

/**
 * Why learning leaves a rule alone.
 */
export type StyleFrozen = "rejected" | "removed" | "reverted" | "edited";

export type StyleLevel = "high" | "medium" | "low";

export type StyleMoment = {
  video: string,
  /**
   * In the recording, or in the finished cut where the rule says so.
   */
  timeUs: number,
  line: string,
};

export type StyleNotLearned = {
  title: string,
  reason: StyleFrozen,
};

/**
 * A raw recording and the finished video the creator cut from it.
 */
export type StylePair = {
  recording: string,
  cut: string,
};

/**
 * How one pair of a style learning job ended, sent as `style-pair`.
 */
export type StylePairResult = {
  jobId: string,
  index: number,
  /**
   * The share of the finished video's speech found in the recording.
   */
  matched: number | null,
  /**
   * Why nothing was learned from the pair.
   */
  error: string | null,
};

export type StyleRule = {
  title: string,
  summary: string,
  /**
   * The creator changed it by hand, so learning leaves it alone.
   */
  byYou: boolean,
  /**
   * How well the videos learned from now back it; none when they no longer show it.
   */
  confidence: StyleConfidence | null,
};

export type StyleSource = {
  title: string,
  kind: StyleSourceKind,
  atMs: number,
  matched: number | null,
};

export type StyleSourceKind = "pair" | "project";

export type StyleVersion = {
  index: number,
  label: string,
  atMs: number,
};

/**
 * The style as the app shows it.
 */
export type StyleView = {
  /**
   * The version shown; saving the text checks it is still the newest.
   */
  version: number,
  /**
   * EDIT.md, none without a style.
   */
  text: string | null,
  /**
   * The creator's own rules.
   */
  own: Array<string>,
  /**
   * Learned rules in the style, in file order.
   */
  rules: Array<StyleRule>,
  suggestions: Array<Suggestion>,
  notLearned: Array<StyleNotLearned>,
  /**
   * Newest first.
   */
  sources: Array<StyleSource>,
  /**
   * Newest first.
   */
  versions: Array<StyleVersion>,
};

/**
 * A sentence said with emphasis, proposed for a punch-in.
 */
export type SuggestedZoom = {
  /**
   * Inclusive word numbers of the transcript view.
   */
  from: number,
  to: number,
  startUs: number,
  endUs: number,
  text: string,
  score: number,
  scale: number,
};

export type Suggestion = {
  title: string,
  summary: string,
  /**
   * The style already has this rule and learning would change it.
   */
  update: boolean,
  changes: Array<StyleChange>,
  confidence: StyleConfidence,
  moments: Array<StyleMoment>,
  /**
   * The rule as EDIT.md would hold it.
   */
  text: string,
};

export type TextStyle = {
  /**
   * Font family name; `None` uses the bundled default, Inter.
   */
  fontFamily?: string | null,
  /**
   * Pixels at canvas resolution.
   */
  fontSize: number,
  /**
   * `#rrggbb`
   */
  color: string,
  bold: boolean,
  /**
   * Outline width in canvas pixels, 0 disables it.
   */
  strokeWidth: number,
  strokeColor: string,
  /**
   * `#rrggbbaa` box behind the text.
   */
  background: string | null,
  /**
   * Lines wrap at this width in canvas pixels; `None` wraps at 90% of the canvas width. Generated captions on
   * vertical videos keep to the Reels and TikTok safe area.
   */
  maxWidth?: number | null,
  /**
   * `#rrggbb` fill of the word being spoken (karaoke captions); `None` draws every word in `color`.
   * Needs the clip's `words`; outline, box, size and wrapping stay the same.
   */
  highlight?: string | null,
};

/**
 * A still made from one frame of the video: a background, the person cut out of the frame, an
 * outline around them and text, some of it behind them. Sizes are in thumbnail pixels.
 */
export type Thumbnail = {
  format: ThumbnailFormat,
  /**
   * The frame, as the video shows it at this timeline time without its text tracks.
   */
  timeUs: number,
  /**
   * Where the frame sits, as for clips: scale 1 fits the whole frame inside the thumbnail, x and y move its
   * centre by fractions of the thumbnail, crop cuts its edges without moving the rest.
   */
  frame: Transform,
  background: ThumbnailBackground,
  /**
   * Bottom to top.
   */
  texts: Array<ThumbnailText>,
  outline?: ThumbnailOutline | null,
};

export type ThumbnailBackground = {
  /**
   * A copy of the frame behind the person: the frame as placed, enlarged about its centre until it covers
   * the thumbnail. False shows only `color`.
   */
  picture: boolean,
  /**
   * Blur of that copy, 0 (sharp) to 1 (strongest).
   */
  blur: number,
  /**
   * How much darker the background gets, 0 (unchanged) to 1 (black).
   */
  dim: number,
  /**
   * `#rrggbb` under everything.
   */
  color: string,
};

export type ThumbnailFormat = "cover_9x16" | "youtube_16x9";

/**
 * A solid line around the person, like a sticker's edge.
 */
export type ThumbnailOutline = {
  /**
   * `#rrggbb` or `#rrggbbaa`
   */
  color: string,
  /**
   * Thumbnail pixels, up to 100.
   */
  width: number,
};

export type ThumbnailText = {
  text: string,
  /**
   * Font size and outline in thumbnail pixels; lines wrap at 90% of the thumbnail width by default.
   */
  style: TextStyle,
  transform: Transform,
  /**
   * Drawn behind the person, so their head can cover part of it.
   */
  behind: boolean,
};

/**
 * Timeline range `[start_us, end_us)`.
 */
export type TimeRange = {
  startUs: number,
  endUs: number,
};

export type Track = {
  id: string,
  kind: TrackKind,
  name: string,
  muted: boolean,
  hidden: boolean,
  /**
   * Ripple cuts leave this track alone, so music keeps playing across them. On for tracks
   * made for audio files, off for everything else, including sound detached from a video.
   */
  keepInPlace: boolean,
  clips: Array<Clip>,
};

export type TrackKind = "video" | "audio" | "text";

export type TranscriptCut = {
  snapshot: Snapshot,
  /**
   * Where the first cut starts, which is now where what followed it plays.
   */
  startUs: number,
  removedUs: number,
};

/**
 * A silence in speech longer than the pause length; shortening it cuts `start_us..end_us`
 * out of the whole `gap_us`.
 */
export type TranscriptPause = {
  startUs: number,
  endUs: number,
  gapUs: number,
};

/**
 * The timeline's speech as it is now, from the transcripts of its media files.
 */
export type TranscriptView = {
  /**
   * Sent back with a cut, which is refused once the speech moved or was recognised again.
   */
  key: string,
  words: Array<TranscriptWord>,
  pauses: Array<TranscriptPause>,
  /**
   * Heard media without a transcript yet.
   */
  untranscribed: Array<string>,
  /**
   * Earlier attempts of restarted sentences, unfinished ones included, and the filler words that
   * start a sentence: what removing retakes cuts besides the pauses.
   */
  retakes: number,
  fillers: number,
};

/**
 * A word where it is heard on the timeline; `i` numbers it for cuts.
 */
export type TranscriptWord = {
  i: number,
  startUs: number,
  endUs: number,
  text: string,
  p: number,
  /**
   * What recognition wrote, when the user corrected the word.
   */
  original?: string,
};

export type Transform = {
  /**
   * Offset of the layer centre from the canvas centre, as a fraction of canvas width.
   */
  x: number,
  /**
   * Offset of the layer centre from the canvas centre, as a fraction of canvas height.
   */
  y: number,
  /**
   * 1.0 fits media inside the canvas; text is drawn at its font size.
   */
  scale: number,
  /**
   * Degrees, clockwise.
   */
  rotation: number,
  opacity: number,
  /**
   * Edges cut off the layer. Part of the transform, so keyframes can animate it.
   */
  crop?: Crop | null,
};

/**
 * Plays across [cut - d/2, cut + d/2]. The outgoing clip continues past its out point
 * (holding its last frame when the source ends) and the incoming clip starts early
 * (holding its first frame), so the timeline length does not change. Audio crossfades.
 */
export type Transition = {
  kind: TransitionKind,
  durationUs: number,
};

export type TransitionKind = "dissolve" | "fadeBlack" | "fadeWhite" | "slideLeft" | "slideUp" | "zoomIn" | "wipeLeft" | "blur";

export type Transport = {
  playing: boolean,
  tUs: number,
};

export type VisionModels = {
  /**
   * Download size of what is missing.
   */
  sizeMb: number,
  downloaded: boolean,
  /**
   * Why covers cannot run on this computer at all, so nothing should be downloaded.
   */
  unavailable: string | null,
};

/**
 * A word as the user corrected it. It applies only while the file's transcript has a word that
 * starts at `source_start_us` with the `original` text: recognised again differently, the
 * correction does nothing, and it never moves to another word.
 */
export type WordCorrection = {
  assetId: string,
  /**
   * Where the word starts in its media file.
   */
  sourceStartUs: number,
  /**
   * The word as recognised.
   */
  original: string,
  text: string,
};

export type WordsCorrected = {
  snapshot: Snapshot,
  /**
   * Caption clips that now show the corrected words.
   */
  captions: number,
};

/**
 * A punch-in over the timeline range `[start_us, end_us)`.
 */
export type ZoomRange = {
  startUs: number,
  endUs: number,
  /**
   * Multiplies the clip's scale; 1.15–1.3 is a subtle punch-in.
   */
  scale: number,
};

export type ZoomSuggestions = {
  /**
   * The transcript key the word numbers belong to; applying is refused once it changed.
   */
  key: string,
  zooms: Array<SuggestedZoom>,
};

export type ZoomsApplied = {
  snapshot: Snapshot,
  /**
   * False when every clip in reach has keyframes, so nothing changed and there is nothing to undo.
   */
  changed: boolean,
  /**
   * Clips with keyframes the zooms left alone.
   */
  skipped: number,
};
