#!/usr/bin/env bash
# Fetches FFmpeg, ALSA and Vulkan development files without root (Fedora/Nobara),
# links them against the system runtime libraries and writes a local
# .cargo/config.toml so `cargo build` and `tauri dev` find them.
#
# System Vulkan development packages or an existing VULKAN_SDK take precedence.
set -euo pipefail

DEPS="${NUZKY_DEPS:-$HOME/.cache/nuzky/deps}"
ROOT="$DEPS/root"
REPO="$(cd "$(dirname "$0")/.." && pwd)"

mkdir -p "$DEPS/rpms"
if ! ls "$DEPS"/rpms/libavcodec-free-devel-*.x86_64.rpm >/dev/null 2>&1; then
  dnf download --arch x86_64 --destdir "$DEPS/rpms" \
    libavcodec-free-devel libavformat-free-devel libavutil-free-devel \
    libswscale-free-devel libswresample-free-devel libavfilter-free-devel \
    libavdevice-free-devel alsa-lib-devel
fi

# Point the unversioned .so symlinks at the installed runtime libraries. Each link changes in one rename,
# because other checkouts may be linking against this tree right now.
link_runtime() {
  for link in "$1"/usr/lib64/*.so; do
    name="$(basename "$link")"
    soname="$(ls /usr/lib64/"$name".* 2>/dev/null | sort | head -1 || true)"
    if [ -n "$soname" ] && [ "$(readlink "$link")" != "$soname" ]; then
      ln -sfn "$soname" "$link.new" && mv -T "$link.new" "$link"
    fi
  done
}

# One setup at a time. The tree is extracted once, aside, and swapped in with a single rename, so a checkout
# that builds meanwhile always finds a whole tree.
exec 7>"$DEPS/.setup.lock"
flock 7
if [ ! -f "$ROOT/.complete" ]; then
  fresh="$(mktemp -d "$DEPS/root.XXXXXX")"
  trap 'rm -rf "$fresh"' EXIT
  (cd "$fresh" && for r in "$DEPS"/rpms/*.x86_64.rpm; do rpm2cpio "$r" | cpio -idm --quiet; done)
  # Rewrite pkg-config paths to where the tree will live.
  for pc in "$fresh"/usr/lib64/pkgconfig/*.pc; do
    sed -i -e "s|^libdir=/usr/lib64|libdir=$ROOT/usr/lib64|" \
           -e "s|^includedir=/usr/include|includedir=$ROOT/usr/include|" "$pc"
  done
  link_runtime "$fresh"
  touch "$fresh/.complete"
  # Afterwards $fresh holds the tree an older setup left, or nothing.
  if [ -e "$ROOT" ]; then mv --exchange -T "$fresh" "$ROOT"; else mv -T "$fresh" "$ROOT"; fi
  rm -rf "$fresh"
  trap - EXIT
fi
link_runtime "$ROOT"
exec 7>&-

SDK="${VULKAN_SDK:-}"
if [ -n "$SDK" ]; then
  test -x "$SDK/bin/glslc" && test -f "$SDK/include/vulkan/vulkan.hpp" \
    && test -f "$SDK/lib/libvulkan.so" || {
    echo "VULKAN_SDK must contain bin/glslc, include/vulkan/vulkan.hpp and lib/libvulkan.so" >&2
    exit 1
  }
elif command -v glslc >/dev/null && pkg-config --exists vulkan; then
  echo "Using system Vulkan development files"
else
  test "$(uname -m)" = x86_64 || {
    echo "Install Vulkan development files for $(uname -m); the downloaded SDK is x86_64 only" >&2
    exit 1
  }
  SDK_VERSION=1.4.363.0
  SDK_SHA256=197962f5cbf80baf2775a03336a01cee7c8745686c65aaa70d3f751ade4d7e43
  SDK_CACHE="$DEPS/vulkan-sdk"
  ARCHIVE="$SDK_CACHE/vulkansdk-linux-x86_64-$SDK_VERSION.tar.xz"
  SDK="$SDK_CACHE/$SDK_VERSION/x86_64"
  mkdir -p "$SDK_CACHE"
  if [ ! -f "$ARCHIVE" ]; then
    curl --fail --location --connect-timeout 15 --max-time 120 --retry 2 \
      "https://sdk.lunarg.com/sdk/download/$SDK_VERSION/linux/$(basename "$ARCHIVE")" \
      --output "$ARCHIVE.part"
    echo "$SDK_SHA256  $ARCHIVE.part" | sha256sum --check
    mv "$ARCHIVE.part" "$ARCHIVE"
  fi
  echo "$SDK_SHA256  $ARCHIVE" | sha256sum --check
  if [ ! -f "$SDK_CACHE/$SDK_VERSION/.ready" ]; then
    tar -xf "$ARCHIVE" -C "$SDK_CACHE" "$SDK_VERSION/x86_64"
    touch "$SDK_CACHE/$SDK_VERSION/.ready"
  fi
  # Use the host loader with its installed drivers, not the SDK's newer runtime.
  VULKAN_LOADER="$(gcc -print-file-name=libvulkan.so.1)"
  test -f "$VULKAN_LOADER" || { echo "System libvulkan.so.1 is required" >&2; exit 1; }
  ln -sf "$VULKAN_LOADER" "$SDK/lib/libvulkan.so"
fi

GCC_INC="$(dirname "$(gcc -print-file-name=include/stddef.h)")"
mkdir -p "$REPO/.cargo"
cat > "$REPO/.cargo/config.toml" <<CFG
# Generated by scripts/setup-linux-deps.sh. Machine specific, not committed.
[env]
PKG_CONFIG_PATH = "$ROOT/usr/lib64/pkgconfig"
LIBCLANG_PATH = "/usr/lib64"
BINDGEN_EXTRA_CLANG_ARGS = "-I$GCC_INC"
CFG
if [ -n "$SDK" ]; then
  cat >> "$REPO/.cargo/config.toml" <<CFG
VULKAN_SDK = "$SDK"
PATH = { value = "$SDK/bin:$PATH", force = true }
# whisper-rs-sys emits -lvulkan on Linux without adding the SDK link directory.
LIBRARY_PATH = { value = "$SDK/lib${LIBRARY_PATH:+:$LIBRARY_PATH}", force = true }
CFG
fi
# ONNX Runtime, which debug builds load from the same deps directory when covers run.
NUZKY_DEPS="$DEPS" node "$REPO/scripts/fetch-onnxruntime.mjs" >/dev/null
echo "Dev dependencies ready in $ROOT"
# A new worktree starts from another worktree's build instead of compiling every dependency again.
bash "$REPO/scripts/seed-target.sh"
