#!/usr/bin/env bash
# Fetches FFmpeg and ALSA development headers without root (Fedora/Nobara),
# links them against the system runtime libraries and writes a local
# .cargo/config.toml so `cargo build` and `tauri dev` find them.
#
# If you have root, `sudo dnf install ffmpeg-free-devel alsa-lib-devel clang`
# does the same and this script is unnecessary.
set -euo pipefail

DEPS="${CAPOPEN_DEPS:-$HOME/.cache/capopen/deps}"
ROOT="$DEPS/root"
REPO="$(cd "$(dirname "$0")/.." && pwd)"

mkdir -p "$DEPS/rpms"
if ! ls "$DEPS"/rpms/libavcodec-free-devel-*.x86_64.rpm >/dev/null 2>&1; then
  dnf download --arch x86_64 --destdir "$DEPS/rpms" \
    libavcodec-free-devel libavformat-free-devel libavutil-free-devel \
    libswscale-free-devel libswresample-free-devel libavfilter-free-devel \
    libavdevice-free-devel alsa-lib-devel
fi

rm -rf "$ROOT" && mkdir -p "$ROOT"
(cd "$ROOT" && for r in "$DEPS"/rpms/*.x86_64.rpm; do rpm2cpio "$r" | cpio -idm --quiet; done)

# Point the unversioned .so symlinks at the installed runtime libraries.
for link in "$ROOT"/usr/lib64/*.so; do
  name="$(basename "$link")"
  soname="$(ls /usr/lib64/"$name".* 2>/dev/null | sort | head -1 || true)"
  [ -n "$soname" ] && ln -sf "$soname" "$link"
done

# Rewrite pkg-config paths to the extracted tree.
for pc in "$ROOT"/usr/lib64/pkgconfig/*.pc; do
  sed -i -e "s|^libdir=/usr/lib64|libdir=$ROOT/usr/lib64|" \
         -e "s|^includedir=/usr/include|includedir=$ROOT/usr/include|" "$pc"
done

GCC_INC="$(dirname "$(gcc -print-file-name=include/stddef.h)")"
mkdir -p "$REPO/.cargo"
cat > "$REPO/.cargo/config.toml" <<CFG
# Generated by scripts/setup-linux-deps.sh. Machine specific, not committed.
[env]
PKG_CONFIG_PATH = "$ROOT/usr/lib64/pkgconfig"
FFMPEG_PKG_CONFIG_PATH = "$ROOT/usr/lib64/pkgconfig"
LIBCLANG_PATH = "/usr/lib64"
BINDGEN_EXTRA_CLANG_ARGS = "-I$GCC_INC"
CFG
echo "Dev dependencies ready in $ROOT"
