//! `src/lib/types.ts` is generated from the Rust types the UI receives and sends, so the two cannot
//! drift apart. `cargo test` fails while the file is out of date, and
//! `NUZKY_WRITE_TYPES=1 cargo test -p nuzky-app typescript_types` writes it again.

use std::any::TypeId;
use std::collections::{BTreeMap, HashSet};

use nuzky_engine::edit::EditCmd;
use nuzky_engine::model::{Canvas, SafeArea};
use ts_rs::{Config, TS, TypeVisitor};

use crate::{Boot, Filmstrip, FontFamilies, LayerBounds};

const PATH: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/../src/lib/types.ts");
const HEADER: &str = "// Generated from the Rust types by src-tauri/src/typescript.rs. Do not edit this file: change the Rust\n// type, then write it again with `NUZKY_WRITE_TYPES=1 cargo test -p nuzky-app typescript_types`.\n";

/// The canvas as the UI receives it. Snapshots add its safe area (`snapshot_project` in lib.rs), which
/// saved projects leave out.
#[derive(TS)]
#[ts(rename = "Canvas", rename_all = "camelCase")]
#[allow(dead_code, reason = "only its TypeScript declaration is used")]
struct SnapshotCanvas {
    #[ts(flatten)]
    canvas: Canvas,
    /// Where Reels and TikTok draw nothing over a vertical video, in canvas pixels; null for other formats.
    safe_area: Option<SafeArea>,
}

/// Every declaration the given types need, by TypeScript name.
struct Declarations<'a> {
    cfg: &'a Config,
    seen: HashSet<TypeId>,
    by_name: BTreeMap<String, String>,
}

impl TypeVisitor for Declarations<'_> {
    fn visit<T: TS + 'static + ?Sized>(&mut self) {
        // Primitives have no declaration, and `SnapshotCanvas` stands in for the saved canvas.
        if T::output_path().is_none()
            || TypeId::of::<T>() == TypeId::of::<Canvas>()
            || !self.seen.insert(TypeId::of::<T>())
        {
            return;
        }
        let name = T::ident(self.cfg);
        let declaration = layout(&format!("{}export {}", T::docs().unwrap_or_default(), T::decl(self.cfg)));
        assert!(
            self.by_name.insert(name.clone(), declaration).is_none(),
            "two Rust types are called {name} in TypeScript"
        );
        T::visit_dependencies(self);
    }
}

/// ts-rs writes each declaration on one line; this puts every object field on its own indented line
/// with its doc comment above it. Strings and comments are copied unchanged.
fn layout(declaration: &str) -> String {
    let mut out = String::new();
    let mut open = Vec::new();
    let mut new_line = false;
    let mut rest = declaration;
    while let Some(c) = rest.chars().next() {
        let depth = open.iter().filter(|&&b| b == '{').count();
        let indent = "  ".repeat(depth);
        if let Some(comment) = rest.strip_prefix("/**") {
            let end = comment.find("*/").expect("doc comments are closed") + 2;
            if !out.is_empty() && !out.ends_with('\n') {
                out.truncate(out.trim_end().len());
                out.push('\n');
            }
            for line in format!("/**{}", &comment[..end]).lines() {
                let line = line.trim();
                let pad = if line.starts_with('*') { " " } else { "" };
                out.push_str(&format!("{indent}{pad}{line}\n"));
            }
            rest = comment[end..].trim_start();
            new_line = false;
            continue;
        }
        let len = if c == '"' { rest[1..].find('"').expect("strings are closed") + 2 } else { c.len_utf8() };
        let token = &rest[..len];
        rest = &rest[len..];
        match c {
            '\n' => continue,
            ' ' if new_line || out.ends_with('\n') => continue,
            '{' | '[' | '<' | '(' => open.push(c),
            '}' => {
                open.pop();
                out.truncate(out.trim_end().len());
                if !out.ends_with('{') {
                    out.push_str(&format!("\n{}", "  ".repeat(depth - 1)));
                }
                out.push('}');
                new_line = false;
                continue;
            }
            ']' | '>' | ')' => {
                open.pop();
            }
            _ => {}
        }
        if new_line {
            out.truncate(out.trim_end().len());
            out.push_str(&format!("\n{indent}"));
        } else if out.ends_with('\n') {
            out.push_str(&indent);
        }
        out.push_str(token);
        new_line = c == '{' || c == ',' && open.last() == Some(&'{');
    }
    out.push('\n');
    out
}

fn generate() -> String {
    // Times, sizes and counters stay far below 2^53, so 64-bit integers are plain JavaScript numbers.
    let cfg = Config::new().with_large_int("number");
    let mut types = Declarations { cfg: &cfg, seen: HashSet::new(), by_name: BTreeMap::new() };
    types.visit::<Boot>();
    types.visit::<SnapshotCanvas>();
    types.visit::<EditCmd>();
    types.visit::<Filmstrip>();
    types.visit::<crate::ProjectVersion>();
    types.visit::<LayerBounds>();
    types.visit::<FontFamilies>();
    types.visit::<crate::jobs::JobEvent>();
    types.visit::<crate::jobs::ExportRequest>();
    types.visit::<crate::jobs::SpeechModel>();
    types.visit::<crate::jobs::VisionModels>();
    types.visit::<crate::store::ProjectSummary>();
    types.visit::<crate::library::Listing>();
    types.visit::<crate::library::DeletedCollection>();
    types.visit::<crate::library::Said>();
    types.visit::<crate::transcripts::TranscriptView>();
    types.visit::<crate::transcripts::TranscriptCut>();
    types.visit::<crate::transcripts::WordsCorrected>();
    types.visit::<crate::zooms::ZoomSuggestions>();
    types.visit::<crate::zooms::ZoomsApplied>();
    types.visit::<crate::connect::Connection>();
    types.visit::<nuzky_mcp::style::StyleView>();
    types.visit::<nuzky_mcp::style::StyleAction>();
    types.visit::<crate::jobs::StylePair>();
    types.visit::<crate::jobs::StylePairResult>();
    types.visit::<crate::cover::CoverView>();
    types.visit::<crate::cover::CoverPick>();
    types.visit::<nuzky_mcp::sounds::Page>();
    types.visit::<crate::sounds::PreviewStarted>();
    types.visit::<crate::sounds::SoundSettings>();
    types.visit::<crate::jobs::StyleTimelineResult>();
    types.visit::<nuzky_mcp::style::TimelinePlan>();
    let mut out = HEADER.to_string();
    for declaration in types.by_name.values() {
        out.push('\n');
        out.push_str(declaration);
    }
    out
}

#[test]
fn typescript_types_match_rust() {
    let generated = generate();
    if std::env::var_os("NUZKY_WRITE_TYPES").is_some() {
        std::fs::write(PATH, &generated).unwrap();
    }
    let written = std::fs::read_to_string(PATH).unwrap_or_default();
    let line = generated.lines().zip(written.lines()).take_while(|(a, b)| a == b).count() + 1;
    assert!(
        written == generated,
        "src/lib/types.ts differs from the Rust types at line {line}. Write it again with \
         `NUZKY_WRITE_TYPES=1 cargo test -p nuzky-app typescript_types`."
    );
}
